ARG alpine_version
ARG ruby_version
FROM ruby:${ruby_version}-alpine${alpine_version}

ARG covalence_version
ARG dumbinit_version
ARG gosu_version
ARG sops_version
ARG prefixout_version

ENV COVALENCE_VERSION $covalence_version
ENV DUMBINIT_VERSION $dumbinit_version
ENV GOSU_VERSION $gosu_version
ENV GOSU_KEY B42F6819007F00F88E364FD4036A9C25BF357DD4
ENV SOPS_VERSION $sops_version
ENV PREFIXOUT_VERSION $prefixout_version

RUN set -ex; \
  \
  fetchDeps=' \
    build-base \
    ca-certificates \
    curl-dev \
    gnupg \
    openssl \
    python-dev \
    ruby-dev \
    unzip \
    wget \
  '; \
  apk add --no-cache --update $fetchDeps && \
  \
  mkdir -p /tmp/build && \
  cd /tmp/build && \
  \
  # Gosu
  wget -O /tmp/build/gosu "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64"; \
  wget -O /tmp/build/gosu.asc "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64.asc"; \
  \
  ( gpg --keyserver ipv4.pool.sks-keyservers.net --receive-keys "$GOSU_KEY" \
  || gpg --keyserver ha.pool.sks-keyservers.net --receive-keys "$GOSU_KEY" ); \
  gpg --batch --verify gosu.asc gosu; \
  chmod +x gosu; \
  \
  # Dumb-init
  wget -O /tmp/build/dumb-init "https://github.com/Yelp/dumb-init/releases/download/v${DUMBINIT_VERSION}/dumb-init_${DUMBINIT_VERSION}_amd64"; \
  chmod +x dumb-init; \
  \
  # Sops
  wget -O /tmp/build/sops "https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux"; \
  chmod +x sops;\
  # prefixout used in covaelnce for logging output of commands delivered
  wget -qO /tmp/prefixout_0.1.0_linux_amd64.zip "https://github.com/unifio/prefixout/releases/download/v0.1.0/prefixout_0.1.0_linux_amd64.zip" && \
  unzip -d /tmp/build /tmp/prefixout_0.1.0_linux_amd64.zip && \
  chmod +x /tmp/build/prefixout;
COPY tools/covalence/Gemfile /tmp/build
COPY tools/covalence/Gemfile.lock /tmp/build
COPY tools/covalence/.gemrc /tmp/build

RUN set -ex; \
  \
  cd /tmp/build && \
  \
  # Ruby Gems
  bundle install --path=/opt/gems --binstubs=/opt/bin --jobs=4 --retry=3

FROM ruby:${ruby_version}-alpine${alpine_version}
LABEL maintainer="Unif.io, Inc. <support@unif.io>"

ARG covalence_version

ENV COVALENCE_VERSION $covalence_version
ENV BUNDLE_GEMFILE /opt/Gemfile
ENV BUNDLE_PATH /opt/gems
ENV PATH /opt/bin:$PATH

COPY --from=0 /tmp/build/gosu /usr/local/bin/
COPY --from=0 /tmp/build/dumb-init /usr/local/bin/
COPY --from=0 /tmp/build/sops /usr/local/bin/
COPY --from=0 /tmp/build/prefixout /usr/local/bin/
COPY --from=0 /tmp/build/Gemfile /opt/
COPY --from=0 /tmp/build/Gemfile.lock /opt/
COPY --from=0 /tmp/build/.gemrc /opt/
COPY --from=0 /opt/gems /opt/gems
COPY --from=0 /opt/bin /opt/bin

RUN set -ex; \
  \
  fetchDeps=' \
    ansible \
    bash \
    build-base \
    ca-certificates \
    curl \
    curl-dev \
    docker \
    git \
    gnupg \
    groff \
    jq \
    less \
    mercurial \
    openssl \
    openssh \
    python-dev \
    python3-dev \
    ruby-dev \
    tar \
    unzip \
    zip \
    wget \
    docker-compose \
  '; \
  apk add --no-cache --update $fetchDeps && \
  # pip
  echo "**** install pip ****" && \
  python3 -m ensurepip && \
  rm -r /usr/lib/python*/ensurepip && \
  pip3 install --no-cache --upgrade pip setuptools wheel && \
  pip3 install --no-cache --upgrade --ignore-installed awscli ec2instanceconnectcli && \
  \
  mkdir -p /tmp/build && \
  cd /tmp/build && \
  \
  # Install glibc
  wget -q -O /etc/apk/keys/sgerrand.rsa.pub "https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub" && \
  wget -q "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk" && \
  apk add glibc-2.29-r0.apk && \
  # Install gem packages
  bundle check --gemfile=/opt/Gemfile --path=/opt/gems || bundle install --binstubs=/opt/bin --gemfile=/opt/Gemfile --path=/opt/gems --jobs=4 --retry=3 && \
  \
  # Cleanup
  cd / && \
  rm -rf /tmp/build

COPY pkr_files/packer* /usr/local/bin/
COPY tf_files/terraform* /usr/local/bin/
COPY tools/covalence/entrypoint.sh /usr/local/bin/

VOLUME /data
WORKDIR /data

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["bundle","exec","rake"]
