ARG alpine_version
ARG ruby_version
FROM ruby:${ruby_version}-alpine${alpine_version}

ARG covalence_version
ARG dumbinit_version
ARG gemfury_token
ARG gosu_version

ENV COVALENCE_VERSION $covalence_version
ENV DUMBINIT_VERSION $dumbinit_version
ENV GOSU_VERSION $gosu_version
ENV GOSU_KEY B42F6819007F00F88E364FD4036A9C25BF357DD4

RUN set -ex; \
  \
  fetchDeps=' \
    build-base \
    ca-certificates \
    curl-dev \
    gnupg \
    openssl \
    python-dev \
    ruby-dev \
    unzip \
    wget \
  '; \
  apk add --no-cache --update $fetchDeps && \
  \
  mkdir -p /tmp/build && \
  cd /tmp/build && \
  \
  # Gosu
  wget -O /tmp/build/gosu "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64"; \
  wget -O /tmp/build/gosu.asc "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64.asc"; \
  \
  keyserver=$(getent ahostsv4 ha.pool.sks-keyservers.net | grep STREAM | head -n 1 | cut -d ' ' -f 1); \
  gpg --keyserver $keyserver --receive-keys $GOSU_KEY; \
  gpg --batch --verify gosu.asc gosu; \
  chmod +x gosu; \
  \
  # Dumb-init
  wget -O /tmp/build/dumb-init "https://github.com/Yelp/dumb-init/releases/download/v${DUMBINIT_VERSION}/dumb-init_${DUMBINIT_VERSION}_amd64"; \
  chmod +x dumb-init

COPY tools/covalence/Gemfile /tmp/build
COPY tools/covalence/Gemfile.lock /tmp/build
COPY tools/covalence/.gemrc /tmp/build

RUN set -ex; \
  \
  cd /tmp/build && \
  \
  # Ruby Gems
  bundle config https://gem.fury.io/unifio/ $gemfury_token && \
  bundle install --path=/opt/gems --jobs=4 --retry=3

FROM ruby:${ruby_version}-alpine${alpine_version}
LABEL maintainer="Unif.io, Inc. <support@unif.io>"

ARG covalence_version
ARG gemfury_token

ENV COVALENCE_VERSION $covalence_version
ENV BUNDLE_GEMFILE /opt/Gemfile
ENV BUNDLE_PATH /opt/gems

COPY --from=0 /tmp/build/gosu /usr/local/bin/
COPY --from=0 /tmp/build/dumb-init /usr/local/bin/
COPY --from=0 /tmp/build/Gemfile /opt/
COPY --from=0 /tmp/build/Gemfile.lock /opt/
COPY --from=0 /tmp/build/.gemrc /opt/
COPY --from=0 /opt/gems /opt/gems

RUN set -ex; \
  \
  fetchDeps=' \
    bash \
    build-base \
    ca-certificates \
    curl \
    curl-dev \
    docker \
    git \
    gnupg \
    groff \
    jq \
    less \
    mercurial \
    openssl \
    openssh \
    python-dev \
    ruby-dev \
    tar \
    unzip \
    wget \
  '; \
  apk add --no-cache --update $fetchDeps && \
  \
  mkdir -p /tmp/build && \
  cd /tmp/build && \
  \
  # Install glibc
  wget -q -O /etc/apk/keys/sgerrand.rsa.pub "https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub" && \
  wget -q "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk" && \
  apk add glibc-2.23-r3.apk && \
  \
  # Install PIP packages
  curl -O https://bootstrap.pypa.io/get-pip.py && \
  python get-pip.py && \
  pip install awscli docker-compose && \
  \
  # Install gem packages
  bundle config https://gem.fury.io/unifio/ $gemfury_token && \
  bundle check --gemfile=/opt/Gemfile --path=/opt/gems || bundle install --gemfile=/opt/Gemfile --path=/opt/gems --jobs=4 --retry=3 && \
  \
  # Cleanup
  cd / && \
  rm -rf /tmp/build

COPY pkr_files/packer* /usr/local/bin/
COPY tf_files/terraform* /usr/local/bin/
COPY other_bins/* /usr/local/bin/
COPY tools/covalence/entrypoint.sh /usr/local/bin/

VOLUME /data
WORKDIR /data

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["bundle","exec","rake"]
