version: '3'
services:
  covalence:
    build:
      context: ./tools/covalence
      args:
        covalence_version: $COVALENCE_VERSION
        alpine_version: $ALPINE_VERSION
        ruby_version: $RUBY_VERSION
    image: "${COVALENCE_REGISTRY:-unifio/covalence}"
  packer:
    build:
      context: ./tools/packer
      args:
        packer_version: $PACKER_VERSION
        alpine_version: $ALPINE_VERSION
    image: "${PACKER_REGISTRY:-unifio/packer}"
  terraform:
    build:
      context: ./tools/terraform
      args:
        terraform_version: $TERRAFORM_VERSION
        alpine_version: $ALPINE_VERSION
    image: "${TERRAFORM_REGISTRY:-unifio/terraform}"
  ci-infra:
    build:
      context: .
      dockerfile: Dockerfile-infra
      args:
        alpine_version: $ALPINE_VERSION
        covalence_version: $COVALENCE_VERSION
        dumbinit_version: $DUMBINIT_VERSION
        gosu_version: $GOSU_VERSION
        ruby_version: $RUBY_VERSION
        sops_version: $SOPS_VERSION
        prefixout_version: $PREFIXOUT_VERSION
    image: "${CI_REGISTRY:-unifio/ci}:latest"
    depends_on:
      - packer
      - terraform
  ci-node:
    build:
      context: .
      dockerfile: Dockerfile-node
      args:
        covalence_version: $COVALENCE_VERSION
        dumbinit_version: $DUMBINIT_VERSION
        gosu_version: $GOSU_VERSION
        node_version: $NODE_VERSION
        sops_version: $SOPS_VERSION
        prefixout_version: $PREFIXOUT_VERSION
    image: "${CI_REGISTRY:-unifio/ci}:latest-node"
    depends_on:
      - packer
      - terraform
