source 'https://rubygems.org' do
  gem 'awesome_print'
  gem 'bigdecimal'
  gem 'ci_reporter_rspec'
  gem 'consul_loader'
  gem 'covalence', ENV['COVALENCE_VERSION'.to_s]
  gem 'dockerspec'
  gem 'dotenv'
  gem 'rspec'
  gem 'rspec_junit_formatter'
  gem 'serverspec'
  gem 'thor'
end
